#####################################
#  B.E.A.R Cassandra 3.10 Kurulumu  #
#####################################

# Set the base image for this installation
FROM centos:7

# File Author / Maintainer
MAINTAINER miwgates <burak_ozel@outlook.com>

# Pre-reqs
RUN yum clean all && \
	yum -y update && \
	rm -rf /var/cache/*
RUN yum provides ifconfig
RUN yum -y install autoconf automake java-1.8.0-openjdk-devel.x86_64 java-1.8.0-openjdk.x86_64 util-linux-ng.x86_64 wget net-tools gcc make zlib-devel.x86_64 openssl-devel

# Application Install
	# Cassandra
RUN mkdir -p /home && \
	cd /home/ && \
	wget http://archive.apache.org/dist/cassandra/3.10/apache-cassandra-3.10-bin.tar.gz && \
	tar xvzf apache-cassandra-3.10-bin.tar.gz && \
	rm -rf apache-cassandra-3.10-bin.tar.gz
	# Python 2.7.13
RUN cd /usr/src && \
	wget https://www.python.org/ftp/python/2.7.13/Python-2.7.13.tgz && \
	tar xzf Python-2.7.13.tgz && \
	cd Python-2.7.13 && \
	./configure --enable-optimizations && \
	make altinstall

# Copy File into Docker
COPY docker-entrypoint.sh /home/
RUN chmod +x /home/docker-entrypoint.sh

# Env Variables
ENV CONFIG_FILE_PATH None
ENV CASSANDRA_CONFIG_FILE_PATH None

# Entrypoint
ENTRYPOINT ["/home/docker-entrypoint.sh"]

# Portları Aç
EXPOSE 7000 7001 7199 9042 9160
